---
- name: Install VM dependencies and configurations
  hosts: kvms
  become: yes
  remote_user: ubuntu
  tasks:
    - name: Install microk8s dependencies (snapd)
      apt:
        name:
          - snapd
        state: present
        update_cache: yes
    - name: Install microk8s via snap
      become: yes
      ansible.builtin.command: snap install microk8s --classic
      args:
        creates: /snap/bin/microk8s
    # - name: Wait until microk8s is ready (run only on vm00)
    #   become: yes
    #   ansible.builtin.command: /snap/bin/microk8s status --wait-ready
    #   register: microk8s_status
    #   retries: 12
    #   delay: 10
    #   until: microk8s_status.rc == 0
    #   when: inventory_hostname == "kvm00" and false
    # - name: Enable microk8s addons (dns, dashboard, registry) on vm00
    #   become: yes
    #   ansible.builtin.command: /snap/bin/microk8s enable dns dashboard registry
    #   register: microk8s_enable
    #   changed_when: microk8s_enable.rc == 0
    #   when: inventory_hostname == "kvm00" and false