---
- name: Install VM dependencies and configurations
  hosts: kvms
  become: yes
  remote_user: ubuntu
  any_errors_fatal: true
  tasks:
    - name: Install microk8s dependencies (snapd)
      apt:
        name:
          - snapd
        state: present
        update_cache: yes
    - name: Install helm via snap
      become: yes
      ansible.builtin.command: snap install helm --classic
      args:
        creates: /snap/bin/helm
    - name: Install microk8s via snap
      become: yes
      ansible.builtin.command: snap install microk8s --classic
      args:
        creates: /snap/bin/microk8s
    - name: Ensure ubuntu is member of microk8s group
      become: yes
      ansible.builtin.user:
        name: ubuntu
        groups: microk8s
        append: yes
    - name: Ensure /home/ubuntu/.kube exists and is owned by ubuntu
      become: yes
      ansible.builtin.file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0700'
        recurse: yes
    - name: Wait until microk8s is ready
      become: yes
      ansible.builtin.command: /snap/bin/microk8s status --wait-ready
      register: microk8s_status
      retries: 12
      delay: 10
      until: microk8s_status.rc == 0
    - name: Enable microk8s addons (dns, dashboard, registry) on vm00
      become: yes
      ansible.builtin.command: /snap/bin/microk8s enable dns dashboard registry
      register: microk8s_enable
      changed_when: "'Enabling' in microk8s_enable.stdout"
      when: inventory_hostname == "kvm00"
    - name: Request join command for this worker
      become: yes
      ansible.builtin.command: /snap/bin/microk8s add-node --format short
      register: microk8s_join_command
      delegate_to: kvm00
      when: inventory_hostname != "kvm00"
    - name: Display join command for worker
      ansible.builtin.debug:
        msg: "{{ microk8s_join_command.stdout }}"
      when: inventory_hostname != "kvm00"
    - name: Join worker node to the cluster
      become: yes
      ansible.builtin.shell: "{{ microk8s_join_command.stdout }} --worker"
      register: microk8s_join_result
      changed_when: microk8s_join_result.rc == 0
      when: inventory_hostname != "kvm00"
